# Generated by Django 3.0.2 on 2020-03-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_harkkatyö', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
