# Generated by Django 3.0.2 on 2020-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_harkkatyö', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skeittispotti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nimi', models.CharField(max_length=200)),
                ('Kaupunginosa', models.CharField(max_length=200)),
                ('Sijainti', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
